import Head from 'next/head'    
import styles from 'src/styles/Home.module.scss'
import { Header } from 'src/components/Header/Header'
import { Aside } from 'src/components/Aside/Aside'
import { Footer } from 'src/components/Footer/Footer'
import { ArticleList } from 'src/components/Main/ArticleList'
import { client } from "libs/client"

export const getServerSideProps = async(context) => {
    const categoryId = context.params.category;
    try {
        const data = await client.get({ endpoint: "article", queries: {filters: `category[equals]${categoryId}`} });
        if (!data.contents[0].category) {
            throw new Error("404: Category is null.");
        }
        const categoryData = await client.get({ endpoint: "category"});
        let categories = [];
        categoryData.contents.map((category) => {
            categories.push({
                id: category.id,
                title: category.title,
                isActive: (category.id === categoryId) ? true: false
            });
        });
        return {
            props: {
                articles: data.contents,
                categories: categories
            }
        }
    } catch(error) {
        console.log(error.message);
        return {
            notFound: true
        }
    }
}

export default function Home({ articles, categories }) {
    let category = categories.find((category) => category.isActive);
    let pageTitle = category.title;
    return (
        <>
            <Head>
                <title>{`${pageTitle} | Blog Template`}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className={styles.gridArea}>
                <Header />
                <Aside categories={categories} />
                <ArticleList articles={articles} categories={categories} pageTitle={pageTitle} />
                <Footer />
            </div>
        </>
    )
}
